# Generated by Django 3.0.5 on 2020-05-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='op_time',
            field=models.TextField(default='0.00'),
            preserve_default=False,
        ),
    ]
