# Generated by Django 3.0.5 on 2020-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_function_op_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='op_time',
        ),
    ]
