# Generated by Django 3.0.5 on 2020-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_remove_function_op_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('op_time', models.TimeField()),
            ],
        ),
    ]
