# Generated by Django 3.0.5 on 2020-05-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_digitalsignature_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalSignature',
        ),
    ]
