# Generated by Django 3.0.5 on 2020-05-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0007_digital_sig_hashing_steg_watermarking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Digital_Sig',
            new_name='DigitalSig',
        ),
    ]
