# Generated by Django 3.0.5 on 2020-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0009_auto_20200505_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.CharField(max_length=4096)),
                ('private', models.CharField(max_length=4096)),
            ],
        ),
        migrations.DeleteModel(
            name='Steg',
        ),
    ]
