# Generated by Django 3.0.5 on 2020-05-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0010_auto_20200505_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsig',
            name='private',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalsig',
            name='public',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
