# Generated by Django 3.0.5 on 2020-05-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0011_auto_20200505_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashing',
            name='hash',
            field=models.CharField(default='', max_length=10096),
            preserve_default=False,
        ),
    ]
