# Generated by Django 3.0.5 on 2020-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0013_auto_20200507_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalsig',
            name='op_time',
        ),
        migrations.RemoveField(
            model_name='hashing',
            name='op_time',
        ),
        migrations.RemoveField(
            model_name='keys',
            name='op_time',
        ),
        migrations.RemoveField(
            model_name='watermarking',
            name='op_time',
        ),
        migrations.AddField(
            model_name='function',
            name='op_time',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
