# Generated by Django 3.0.5 on 2020-05-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0014_auto_20200507_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermarking',
            name='x',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='watermarking',
            name='y',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='watermarking',
            name='z',
            field=models.IntegerField(default=12),
        ),
    ]
