# Generated by Django 3.0.5 on 2020-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0015_auto_20200507_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermarking',
            name='z',
        ),
        migrations.AddField(
            model_name='watermarking',
            name='mark_text',
            field=models.CharField(default='Watermarking', max_length=4096),
            preserve_default=False,
        ),
    ]
