# Generated by Django 3.0.5 on 2020-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0016_auto_20200507_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermarking',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
    ]
